#pragma once
#include <unordered_map>

#include "GLFW/glfw3.h"                                                         

namespace input
{
   enum class InputKey : uint8_t
   {
      //Keyboard keys

      Space,
      Apostrophe,
      Comma,
      Minus,
      Period,
      Slash,
      _0,
      _1,
      _2,
      _3,
      _4,
      _5,
      _6,
      _7,
      _8,
      _9,
      Semicolon,
      Equal,
      A,
      B,
      C,
      D,
      E,
      F,
      G,
      H,
      I,
      J,
      K,
      L,
      M,
      N,
      O,
      P,
      Q,
      R,
      S,
      T,
      U,
      V,
      W,
      X,
      Y,
      Z,
      LeftBracket,
      BackSlash,
      RightBracket,
      GraveAccent,
      Escape,
      Enter,
      Tab,
      Backspace,
      Insert,
      Delete,
      Right,
      Left,
      Down,
      Up,
      Page_up,
      Page_down,
      Home,
      End,
      Caps_lock,
      Scroll_lock,
      Num_lock,
      Print_screen,
      Pause,
      F1,
      F2,
      F3,
      F4,
      F5,
      F6,
      F7,
      F8,
      F9,
      F10,
      F11,
      F12,
      F13,
      F14,
      F15,
      F16,
      F17,
      F18,
      F19,
      F20,
      F21,
      F22,
      F23,
      F24,
      F25,
      KeyPad_0,
      KeyPad_1,
      KeyPad_2,
      KeyPad_3,
      KeyPad_4,
      KeyPad_5,
      KeyPad_6,
      KeyPad_7,
      KeyPad_8,
      KeyPad_9,
      KeyPad_Decimal,
      KeyPad_Divide,
      KeyPad_Multiply,
      KeyPad_Subtract,
      KeyPad_Add,
      KeyPad_Enter,
      KeyPad_Equal,
      LeftShift,
      LeftControl,
      LeftAlt,
      RightShift,
      RightControl,
      RightAlt,

      LastKeyboardKey = RightAlt,

      //Mouse buttons

      M_Left,
      M_Right,
      M_Middle,
      M_4,
      M_5,
      M_6,
      M_7,
      M_8,

      LastMouseButton = M_8,

      LAST_ENUM_ELEMENT
   };

   namespace mapping
   {
      static std::unordered_map<uint8_t, InputKey> g_GlfwInputKeyMap =
      {
         { GLFW_KEY_SPACE, InputKey::Space },
         { GLFW_KEY_APOSTROPHE, InputKey::Apostrophe },
         { GLFW_KEY_COMMA, InputKey::Comma },
         { GLFW_KEY_MINUS, InputKey::Minus },
         { GLFW_KEY_PERIOD, InputKey::Period },
         { GLFW_KEY_SLASH, InputKey::Slash },
         { GLFW_KEY_0, InputKey::_0 },
         { GLFW_KEY_1, InputKey::_1 },
         { GLFW_KEY_2, InputKey::_2 },
         { GLFW_KEY_3, InputKey::_3 },
         { GLFW_KEY_4, InputKey::_4 },
         { GLFW_KEY_5, InputKey::_5 },
         { GLFW_KEY_6, InputKey::_6 },
         { GLFW_KEY_7, InputKey::_7 },
         { GLFW_KEY_8, InputKey::_8 },
         { GLFW_KEY_9, InputKey::_9 },
         { GLFW_KEY_SEMICOLON, InputKey::Semicolon },
         { GLFW_KEY_EQUAL, InputKey::Equal },
         { GLFW_KEY_A, InputKey::A },
         { GLFW_KEY_B, InputKey::B },
         { GLFW_KEY_C, InputKey::C },
         { GLFW_KEY_D, InputKey::D },
         { GLFW_KEY_E, InputKey::E },
         { GLFW_KEY_F, InputKey::F },
         { GLFW_KEY_G, InputKey::G },
         { GLFW_KEY_H, InputKey::H },
         { GLFW_KEY_I, InputKey::I },
         { GLFW_KEY_J, InputKey::J },
         { GLFW_KEY_K, InputKey::K },
         { GLFW_KEY_L, InputKey::L },
         { GLFW_KEY_M, InputKey::M },
         { GLFW_KEY_N, InputKey::N },
         { GLFW_KEY_O, InputKey::O },
         { GLFW_KEY_P, InputKey::P },
         { GLFW_KEY_Q, InputKey::Q },
         { GLFW_KEY_R, InputKey::R },
         { GLFW_KEY_S, InputKey::S },
         { GLFW_KEY_T, InputKey::T },
         { GLFW_KEY_U, InputKey::U },
         { GLFW_KEY_V, InputKey::V },
         { GLFW_KEY_W, InputKey::W },
         { GLFW_KEY_X, InputKey::X },
         { GLFW_KEY_Y, InputKey::Y },
         { GLFW_KEY_Z, InputKey::Z },
         { GLFW_KEY_LEFT_BRACKET, InputKey::LeftBracket },
         { GLFW_KEY_BACKSLASH, InputKey::BackSlash },
         { GLFW_KEY_RIGHT_BRACKET, InputKey::RightBracket },
         { GLFW_KEY_GRAVE_ACCENT, InputKey::GraveAccent },
         { GLFW_KEY_ESCAPE, InputKey::Escape },
         { GLFW_KEY_ENTER, InputKey::Enter },
         { GLFW_KEY_TAB, InputKey::Tab },
         { GLFW_KEY_BACKSPACE, InputKey::Backspace },
         { GLFW_KEY_INSERT, InputKey::Insert },
         { GLFW_KEY_DELETE, InputKey::Delete },
         { GLFW_KEY_RIGHT, InputKey::Right },
         { GLFW_KEY_LEFT, InputKey::Left },
         { GLFW_KEY_DOWN, InputKey::Down },
         { GLFW_KEY_UP, InputKey::Up },
         { GLFW_KEY_PAGE_UP, InputKey::Page_up },
         { GLFW_KEY_PAGE_DOWN, InputKey::Page_down },
         { GLFW_KEY_HOME, InputKey::Home },
         { GLFW_KEY_END, InputKey::End },
         { GLFW_KEY_CAPS_LOCK, InputKey::Caps_lock },
         { GLFW_KEY_SCROLL_LOCK, InputKey::Scroll_lock },
         { GLFW_KEY_NUM_LOCK, InputKey::Num_lock },
         { GLFW_KEY_PRINT_SCREEN, InputKey::Print_screen },
         { GLFW_KEY_PAUSE, InputKey::Pause },
         { GLFW_KEY_F1, InputKey::F1 },
         { GLFW_KEY_F2, InputKey::F2 },
         { GLFW_KEY_F3, InputKey::F3 },
         { GLFW_KEY_F4, InputKey::F4 },
         { GLFW_KEY_F5, InputKey::F5 },
         { GLFW_KEY_F6, InputKey::F6 },
         { GLFW_KEY_F7, InputKey::F7 },
         { GLFW_KEY_F8, InputKey::F8 },
         { GLFW_KEY_F9, InputKey::F9 },
         { GLFW_KEY_F10, InputKey::F10 },
         { GLFW_KEY_F11, InputKey::F11 },
         { GLFW_KEY_F12, InputKey::F12 },
         { GLFW_KEY_F13, InputKey::F13 },
         { GLFW_KEY_F14, InputKey::F14 },
         { GLFW_KEY_F15, InputKey::F15 },
         { GLFW_KEY_F16, InputKey::F16 },
         { GLFW_KEY_F17, InputKey::F17 },
         { GLFW_KEY_F18, InputKey::F18 },
         { GLFW_KEY_F19, InputKey::F19 },
         { GLFW_KEY_F20, InputKey::F20 },
         { GLFW_KEY_F21, InputKey::F21 },
         { GLFW_KEY_F22, InputKey::F22 },
         { GLFW_KEY_F23, InputKey::F23 },
         { GLFW_KEY_F24, InputKey::F24 },
         { GLFW_KEY_F25, InputKey::F25 },
         { GLFW_KEY_KP_0, InputKey::KeyPad_0 },
         { GLFW_KEY_KP_1, InputKey::KeyPad_1 },
         { GLFW_KEY_KP_2, InputKey::KeyPad_2 },
         { GLFW_KEY_KP_3, InputKey::KeyPad_3 },
         { GLFW_KEY_KP_4, InputKey::KeyPad_4 },
         { GLFW_KEY_KP_5, InputKey::KeyPad_5 },
         { GLFW_KEY_KP_6, InputKey::KeyPad_6 },
         { GLFW_KEY_KP_7, InputKey::KeyPad_7 },
         { GLFW_KEY_KP_8, InputKey::KeyPad_8 },
         { GLFW_KEY_KP_9, InputKey::KeyPad_9 },
         { GLFW_KEY_KP_DECIMAL, InputKey::KeyPad_Decimal },
         { GLFW_KEY_KP_DIVIDE, InputKey::KeyPad_Divide },
         { GLFW_KEY_KP_MULTIPLY, InputKey::KeyPad_Multiply },
         { GLFW_KEY_KP_SUBTRACT, InputKey::KeyPad_Subtract },
         { GLFW_KEY_KP_ADD, InputKey::KeyPad_Add },
         { GLFW_KEY_KP_ENTER, InputKey::KeyPad_Enter },
         { GLFW_KEY_KP_EQUAL, InputKey::KeyPad_Equal },
         { GLFW_KEY_LEFT_SHIFT, InputKey::LeftShift },
         { GLFW_KEY_LEFT_CONTROL, InputKey::LeftControl },
         { GLFW_KEY_LEFT_ALT, InputKey::LeftAlt },
         { GLFW_KEY_RIGHT_SHIFT, InputKey::RightShift },
         { GLFW_KEY_RIGHT_CONTROL, InputKey::RightControl },
         { GLFW_KEY_RIGHT_ALT, InputKey::RightAlt },

         { GLFW_MOUSE_BUTTON_1 + (uint8_t)InputKey::LastKeyboardKey + 1, InputKey::M_Left  },
         { GLFW_MOUSE_BUTTON_2 + (uint8_t)InputKey::LastKeyboardKey + 1, InputKey::M_Right },
         { GLFW_MOUSE_BUTTON_3 + (uint8_t)InputKey::LastKeyboardKey + 1, InputKey::M_Middle },
         { GLFW_MOUSE_BUTTON_4 + (uint8_t)InputKey::LastKeyboardKey + 1, InputKey::M_4 },
         { GLFW_MOUSE_BUTTON_5 + (uint8_t)InputKey::LastKeyboardKey + 1, InputKey::M_5 },
         { GLFW_MOUSE_BUTTON_6 + (uint8_t)InputKey::LastKeyboardKey + 1, InputKey::M_6 },
         { GLFW_MOUSE_BUTTON_7 + (uint8_t)InputKey::LastKeyboardKey + 1, InputKey::M_7 },
         { GLFW_MOUSE_BUTTON_8 + (uint8_t)InputKey::LastKeyboardKey + 1, InputKey::M_8 }
      };
   }
}