#pragma once
#include <unordered_map>

#include "GLFW/glfw3.h"                                                         

namespace input
{
   enum class Key : uint16_t
   {
      Space,
      Apostrophe,
      Comma,
      Minus,
      Period,
      Slash,
      _0,
      _1,
      _2,
      _3,
      _4,
      _5,
      _6,
      _7,
      _8,
      _9,
      Semicolon,
      Equal,
      A,
      B,
      C,
      D,
      E,
      F,
      G,
      H,
      I,
      J,
      K,
      L,
      M,
      N,
      O,
      P,
      Q,
      R,
      S,
      T,
      U,
      V,
      W,
      X,
      Y,
      Z,
      LeftBracket,
      BackSlash,
      RightBracket,
      GraveAccent,
      Escape,
      Enter,
      Tab,
      Backspace,
      Insert,
      Delete,
      Right,
      Left,
      Down,
      Up,
      Page_up,
      Page_down,
      Home,
      End,
      Caps_lock,
      Scroll_lock,
      Num_lock,
      Print_screen,
      Pause,
      F1,
      F2,
      F3,
      F4,
      F5,
      F6,
      F7,
      F8,
      F9,
      F10,
      F11,
      F12,
      F13,
      F14,
      F15,
      F16,
      F17,
      F18,
      F19,
      F20,
      F21,
      F22,
      F23,
      F24,
      F25,
      KeyPad_0,
      KeyPad_1,
      KeyPad_2,
      KeyPad_3,
      KeyPad_4,
      KeyPad_5,
      KeyPad_6,
      KeyPad_7,
      KeyPad_8,
      KeyPad_9,
      KeyPad_Decimal,
      KeyPad_Divide,
      KeyPad_Multiply,
      KeyPad_Subtract,
      KeyPad_Add,
      KeyPad_Enter,
      KeyPad_Equal,
      LeftShift,
      LeftControl,
      LeftAlt,
      RightShift,
      RightControl,
      RightAlt,

      LAST_ENUM_ELEMENT
   };

   namespace mapping
   {
      static std::unordered_map<uint16_t, Key> g_GlfwKeyMap =
      {
         { GLFW_KEY_SPACE, Key::Space },
         { GLFW_KEY_APOSTROPHE, Key::Apostrophe },
         { GLFW_KEY_COMMA, Key::Comma },
         { GLFW_KEY_MINUS, Key::Minus },
         { GLFW_KEY_PERIOD, Key::Period },
         { GLFW_KEY_SLASH, Key::Slash },
         { GLFW_KEY_0, Key::_0 },
         { GLFW_KEY_1, Key::_1 },
         { GLFW_KEY_2, Key::_2 },
         { GLFW_KEY_3, Key::_3 },
         { GLFW_KEY_4, Key::_4 },
         { GLFW_KEY_5, Key::_5 },
         { GLFW_KEY_6, Key::_6 },
         { GLFW_KEY_7, Key::_7 },
         { GLFW_KEY_8, Key::_8 },
         { GLFW_KEY_9, Key::_9 },
         { GLFW_KEY_SEMICOLON, Key::Semicolon },
         { GLFW_KEY_EQUAL, Key::Equal },
         { GLFW_KEY_A, Key::A },
         { GLFW_KEY_B, Key::B },
         { GLFW_KEY_C, Key::C },
         { GLFW_KEY_D, Key::D },
         { GLFW_KEY_E, Key::E },
         { GLFW_KEY_F, Key::F },
         { GLFW_KEY_G, Key::G },
         { GLFW_KEY_H, Key::H },
         { GLFW_KEY_I, Key::I },
         { GLFW_KEY_J, Key::J },
         { GLFW_KEY_K, Key::K },
         { GLFW_KEY_L, Key::L },
         { GLFW_KEY_M, Key::M },
         { GLFW_KEY_N, Key::N },
         { GLFW_KEY_O, Key::O },
         { GLFW_KEY_P, Key::P },
         { GLFW_KEY_Q, Key::Q },
         { GLFW_KEY_R, Key::R },
         { GLFW_KEY_S, Key::S },
         { GLFW_KEY_T, Key::T },
         { GLFW_KEY_U, Key::U },
         { GLFW_KEY_V, Key::V },
         { GLFW_KEY_W, Key::W },
         { GLFW_KEY_X, Key::X },
         { GLFW_KEY_Y, Key::Y },
         { GLFW_KEY_Z, Key::Z },
         { GLFW_KEY_LEFT_BRACKET, Key::LeftBracket },
         { GLFW_KEY_BACKSLASH, Key::BackSlash },
         { GLFW_KEY_RIGHT_BRACKET, Key::RightBracket },
         { GLFW_KEY_GRAVE_ACCENT, Key::GraveAccent },
         { GLFW_KEY_ESCAPE, Key::Escape },
         { GLFW_KEY_ENTER, Key::Enter },
         { GLFW_KEY_TAB, Key::Tab },
         { GLFW_KEY_BACKSPACE, Key::Backspace },
         { GLFW_KEY_INSERT, Key::Insert },
         { GLFW_KEY_DELETE, Key::Delete },
         { GLFW_KEY_RIGHT, Key::Right },
         { GLFW_KEY_LEFT, Key::Left },
         { GLFW_KEY_DOWN, Key::Down },
         { GLFW_KEY_UP, Key::Up },
         { GLFW_KEY_PAGE_UP, Key::Page_up },
         { GLFW_KEY_PAGE_DOWN, Key::Page_down },
         { GLFW_KEY_HOME, Key::Home },
         { GLFW_KEY_END, Key::End },
         { GLFW_KEY_CAPS_LOCK, Key::Caps_lock },
         { GLFW_KEY_SCROLL_LOCK, Key::Scroll_lock },
         { GLFW_KEY_NUM_LOCK, Key::Num_lock },
         { GLFW_KEY_PRINT_SCREEN, Key::Print_screen },
         { GLFW_KEY_PAUSE, Key::Pause },
         { GLFW_KEY_F1, Key::F1 },
         { GLFW_KEY_F2, Key::F2 },
         { GLFW_KEY_F3, Key::F3 },
         { GLFW_KEY_F4, Key::F4 },
         { GLFW_KEY_F5, Key::F5 },
         { GLFW_KEY_F6, Key::F6 },
         { GLFW_KEY_F7, Key::F7 },
         { GLFW_KEY_F8, Key::F8 },
         { GLFW_KEY_F9, Key::F9 },
         { GLFW_KEY_F10, Key::F10 },
         { GLFW_KEY_F11, Key::F11 },
         { GLFW_KEY_F12, Key::F12 },
         { GLFW_KEY_F13, Key::F13 },
         { GLFW_KEY_F14, Key::F14 },
         { GLFW_KEY_F15, Key::F15 },
         { GLFW_KEY_F16, Key::F16 },
         { GLFW_KEY_F17, Key::F17 },
         { GLFW_KEY_F18, Key::F18 },
         { GLFW_KEY_F19, Key::F19 },
         { GLFW_KEY_F20, Key::F20 },
         { GLFW_KEY_F21, Key::F21 },
         { GLFW_KEY_F22, Key::F22 },
         { GLFW_KEY_F23, Key::F23 },
         { GLFW_KEY_F24, Key::F24 },
         { GLFW_KEY_F25, Key::F25 },
         { GLFW_KEY_KP_0, Key::KeyPad_0 },
         { GLFW_KEY_KP_1, Key::KeyPad_1 },
         { GLFW_KEY_KP_2, Key::KeyPad_2 },
         { GLFW_KEY_KP_3, Key::KeyPad_3 },
         { GLFW_KEY_KP_4, Key::KeyPad_4 },
         { GLFW_KEY_KP_5, Key::KeyPad_5 },
         { GLFW_KEY_KP_6, Key::KeyPad_6 },
         { GLFW_KEY_KP_7, Key::KeyPad_7 },
         { GLFW_KEY_KP_8, Key::KeyPad_8 },
         { GLFW_KEY_KP_9, Key::KeyPad_9 },
         { GLFW_KEY_KP_DECIMAL, Key::KeyPad_Decimal },
         { GLFW_KEY_KP_DIVIDE, Key::KeyPad_Divide },
         { GLFW_KEY_KP_MULTIPLY, Key::KeyPad_Multiply },
         { GLFW_KEY_KP_SUBTRACT, Key::KeyPad_Subtract },
         { GLFW_KEY_KP_ADD, Key::KeyPad_Add },
         { GLFW_KEY_KP_ENTER, Key::KeyPad_Enter },
         { GLFW_KEY_KP_EQUAL, Key::KeyPad_Equal },
         { GLFW_KEY_LEFT_SHIFT, Key::LeftShift },
         { GLFW_KEY_LEFT_CONTROL, Key::LeftControl },
         { GLFW_KEY_LEFT_ALT, Key::LeftAlt },
         { GLFW_KEY_RIGHT_SHIFT, Key::RightShift },
         { GLFW_KEY_RIGHT_CONTROL, Key::RightControl },
         { GLFW_KEY_RIGHT_ALT, Key::RightAlt }
      };
   }
}